spring:
  datasource:
    url: jdbc:postgresql://dpg-cpaav8sf7o1s73adpfhg-a.oregon-postgres.render.com/postgres_demo_czm1
    username: postgres_demo_czm1_user
    password: PRFo4ItYa2asN9Brm7GIXkAup6T3gIl4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # ===Spring-Boot-API-Security-JWT===
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

